language: ruby
before_install:
  - gem install bundler
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-19mode
